#!/bin/bash

# 用法:
# 01 gpuu   	# 查询所有信息,每3s输出一次
# 02 gpuu 2 	# 查询所有信息,每2s输出一次
# 03 gpuu -u 	# 只查询进程信息,每3s输出一次
# 04 gpuu 1 -u  # 只查询进程信息,每1s输出一次, 如果用gpuu -u 1, 则1会被忽略掉

sec=3   # 设置查询的默认间隔(s)

if [ $# -ge 1 -a ! "$1" == "-u" ];then   # 如果参数数目>=1个，且$1不是'-u',则认为$1是间隔时间(s)
    sec=$1
fi
 
k=1
while :
do
    echo "第 $k 次查询!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

    if [ "$2" == "-u" -o "$1" == "-u" ];then
        nvidia-smi | grep " [0-4] .* [CG] \| Type \||=*|"
        echo    # 输出换行
    else
        nvidia-smi
    fi
    sleep $sec
    let k=k+1
done
